### ISSUE TITLE
UI cleanup

### ISSUE THREAD

**Issue by pauldpearson** [pauldpearson/winecellar-webapp#122]

**Comment by pauldpearson** [comment]
add th:if statements to details pages
standardize tables across most details pages
minimize h tags for smaller screens

**Comment by jesperpedersen** [comment]
I did a clean up of the HTML in https://github.com/pauldpearson/winecellar-webapp/commit/0dda0708f0a01855836f30183a4e527a44ce7096

**Comment by pauldpearson** [comment]
Should close after this https://github.com/pauldpearson/winecellar-webapp/commit/a5082bbe644567f0c0b9ebd5633156ddb95ab8e1
